name: Test Next.js web application
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test-project:
    name: Test project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: ./front-end/.node-version
    - name: Install NPM dependencies
      run: yarn install
    - name: Test project
      run: yarn test

